[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n"
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}## [Unreleased]{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.footer %} ({{ commit.footer }}){% endif %}
{% endfor %}
{% endfor %}
"""
footer = """
[unreleased]: https://github.com/{{ repo }}/compare/{{ latest_tag }}...HEAD
{% for tag, prev in tags | reverse | pairwise %}
[{{ tag | trim_start_matches(pat="v") }}]: https://github.com/{{ repo }}/compare/{{ prev }}...{{ tag }}
{% endfor %}
"""

[git]
conventional_commits = true
filter_unconventional = true
