site:
  title: Vulnlog Documentation
  url: https://vulnlog.dev/docs
  start_page: vulnlog::index.adoc

content:
  sources:
    - url: .
      branches:
        - docs/0.13
        - docs/0.12.0
      start_path: docs

## Only use this for local testing
#content:
#  sources:
#    - url: ../vulnlog
#      branches:
#        - docs/0.13
#        - docs/0.12.0
#      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui

output:
  dir: ./build/docs
