site:
  title: Vulnlog Documentation (local)
  url: https://vulnlog.dev/docs
  start_page: vulnlog::index.adoc

content:
  sources:
    - url: ../vulnlog
      branches:
        - HEAD
      worktrees: '.'
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui

output:
  dir: ./build/docs
