// Copyright the Vulnlog contributors
// SPDX-License-Identifier: Apache-2.0

package dev.vulnlog.lib.codec.suppression

import dev.vulnlog.lib.codec.suppression.cargoaudit.CargoAuditSuppressionEncoder
import dev.vulnlog.lib.codec.suppression.generic.GenericSuppressionEncoder
import dev.vulnlog.lib.codec.suppression.snyk.SnykSuppressionEncoder
import dev.vulnlog.lib.codec.suppression.trivy.TrivySuppressionEncoder
import dev.vulnlog.lib.model.suppress.SuppressionOutput

data class SuppressionFile(
    val fileName: String,
    val content: String,
)

private const val GENERATED_BY = "# Generated by Vulnlog (https://vulnlog.dev). DO NOT EDIT.\n"

object SuppressionEncoder {
    fun encode(output: SuppressionOutput): SuppressionFile =
        when (output) {
            is SuppressionOutput.GenericSuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GenericSuppressionEncoder.encode(output),
                )

            is SuppressionOutput.TrivySuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GENERATED_BY + TrivySuppressionEncoder.encode(output),
                )

            is SuppressionOutput.SnykSuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GENERATED_BY + SnykSuppressionEncoder.encode(output),
                )

            is SuppressionOutput.CargoAuditSuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GENERATED_BY + CargoAuditSuppressionEncoder.encode(output),
                )
        }
}
