// Copyright the Vulnlog contributors
// SPDX-License-Identifier: Apache-2.0

package dev.vulnlog.lib.codec.suppression

import dev.vulnlog.lib.codec.suppression.cargoaudit.CargoAuditSuppressionEncoder
import dev.vulnlog.lib.codec.suppression.generic.GenericSuppressionEncoder
import dev.vulnlog.lib.codec.suppression.snyk.SnykSuppressionEncoder
import dev.vulnlog.lib.codec.suppression.trivy.TrivySuppressionEncoder
import dev.vulnlog.lib.model.suppression.SuppressionFormat
import dev.vulnlog.lib.model.suppression.SuppressionList

private const val GENERATED_BY = "# Generated by Vulnlog (https://vulnlog.dev). DO NOT EDIT.\n"

object SuppressionEncoder {
    /** JSON has no comments, so the generic file goes without the header. */
    fun encode(list: SuppressionList): String =
        when (list.format) {
            is SuppressionFormat.Generic -> GenericSuppressionEncoder.encode(list)
            SuppressionFormat.Trivy -> GENERATED_BY + TrivySuppressionEncoder.encode(list)
            SuppressionFormat.Snyk -> GENERATED_BY + SnykSuppressionEncoder.encode(list)
            SuppressionFormat.CargoAudit -> GENERATED_BY + CargoAuditSuppressionEncoder.encode(list)
        }
}
