[versions]
cliktVersion = "5.0.3"
detektVersion = "1.23.7"
koinVersion = "4.0.4"
kotestExtensionKoinVersion = "1.3.0"
kotestVersion = "5.8.1"
kotlinCoroutinesVersion = "1.8.1"
kotlinVersion = "2.2.0"
kotlinxSerializationJsonVersion = "1.8.0"
ktlintVersion = "12.1.1"
mockkVersion = "1.13.10"
owaspDependencyCheckerVersion = "9.2.0"
snykVersion = "0.6.1"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "cliktVersion" }
dependencyCheckGradle = { module = "org.owasp:dependency-check-gradle", version.ref = "owaspDependencyCheckerVersion" }
detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektVersion" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koinVersion" }
koinTestJuint5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koinVersion" }
kotestAssertionsCoreJvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotestVersion" }
kotestExtensionsKoin = { module = "io.kotest.extensions:kotest-extensions-koin", version.ref = "kotestExtensionKoinVersion" }
kotestRunnerJunit5Jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotestVersion" }
kotlinCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlinScriptingCommon = { module = "org.jetbrains.kotlin:kotlin-scripting-common", version.ref = "kotlinVersion" }
kotlinScriptingJvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm", version.ref = "kotlinVersion" }
kotlinScriptingJvmHost = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlinVersion" }
kotlinxSerializationGradlePlugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlinVersion" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
ktlintGradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintVersion" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
snykGradlePlugin = { module = "gradle.plugin.io.snyk.gradle.plugin:snyk", version.ref = "snykVersion" }

[bundles]
kotlinScriptDefinition = ["kotlinScriptingJvm"]
kotlinScript = ["kotlinScriptingCommon", "kotlinScriptingJvm", "kotlinScriptingJvmHost"]

[plugins]
