// Copyright the Vulnlog contributors
// SPDX-License-Identifier: Apache-2.0

package dev.vulnlog.lib.parse.suppression

import dev.vulnlog.lib.model.suppress.SuppressionOutput
import dev.vulnlog.lib.parse.suppression.cargoaudit.CargoAuditSuppressionWriter
import dev.vulnlog.lib.parse.suppression.generic.GenericSuppressionWriter
import dev.vulnlog.lib.parse.suppression.snyk.SnykSuppressionWriter
import dev.vulnlog.lib.parse.suppression.trivy.TrivySuppressionWriter

data class SuppressionFile(
    val fileName: String,
    val content: String,
)

private const val GENERATED_BY = "# Generated by Vulnlog (https://vulnlog.dev). DO NOT EDIT.\n"

object SuppressionWriter {
    fun writeSuppressionOutput(output: SuppressionOutput): SuppressionFile =
        when (output) {
            is SuppressionOutput.GenericSuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GenericSuppressionWriter.write(output),
                )

            is SuppressionOutput.TrivySuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GENERATED_BY + TrivySuppressionWriter.write(output),
                )

            is SuppressionOutput.SnykSuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GENERATED_BY + SnykSuppressionWriter.write(output),
                )

            is SuppressionOutput.CargoAuditSuppression ->
                SuppressionFile(
                    fileName = output.fileName,
                    content = GENERATED_BY + CargoAuditSuppressionWriter.write(output),
                )
        }
}
