= vulnlog suppress

Generates suppression files for SCA scanners.
These files contain vulnerability identifiers that instruct the scanner to exclude the corresponding findings.

[source]
----
vulnlog suppress <file> [flags]
----

[cols="2,3"]
|===
| Flag | Description

| `-o, --output <path>`
| Output directory, or `-` to write to stdout. Defaults to current directory.

| `--reporter <value>`
| Filter on reporter.

| `--release <text>`
| Filter on release, include all releases up to and including that release.

| `--tag <text>`
| Filter on tags. Use multiple times to filter on multiple tags.

| `-`
| Use as the file argument to read from STDIN.

|===

.Create suppression files for all reporters
[source]
----
vulnlog suppress full-example.vl.yaml
Suppression file created at: .snyk
Suppression file created at: .trivyignore.yaml
----

.Create suppression for releases up to and including 8.1.1 and reporter snyk
[source]
----
vulnlog suppress full-example.vl.yaml --release 8.1.1 --reporter snyk
Suppression file created at: .snyk
----

.Read from STDIN and write to STDOUT.
[source]
----
vulnlog suppress --reporter trivy - -o - < full-example.vl.yaml > .myTrivy
----

NOTE: Writing to stdout with `-o -` requires `--reporter` to select a single reporter.
Multiple suppression files cannot be written to stdout simultaneously.

== Output Examples

.Generated Snyk suppression file
[source,yaml]
----
include::{examplesdir}/suppress/Snyk Suppression Example.yaml[lines=1..5]
----

.Generated Trivy suppression file
[source,yaml]
----
include::{examplesdir}/suppress/Trivy Suppression Example.yaml[lines=1..4]
----
