= vulnlog suppress

Create suppression files for various SCA scanners.
These files, also known as ignore files, contain vulnerability identifiers and advise the dependency scanner to not report the findings again.

[source]
----
vulnlog suppress <file> [flags]
----

[cols="2,3"]
|===
| Flag | Description

| `-o, --output <path>`
| Output directory, or `-` to write to stdout. Defaults to current directory.

| `--reporter <value>`
| Filter on reporter.

| `--release <text>`
| Filter on release, include all releases up to and including that release.

| `--tag <text>`
| Filter on tags. Use multiple times to filter on multiple tags.

| `-`
| Use as the file argument to read from STDIN.

|===

.Create suppression files for all reporters
[source]
----
vulnlog suppress full-example.vl.yaml
Suppression file created at: .snyk
Suppression file created at: .trivyignore.yaml
----

.Create suppression for releases up to and including 8.1.1 and reporter snyk
[source]
----
vulnlog suppress full-example.vl.yaml --release 8.1.1 --reporter snyk
Suppression file created at: .snyk
----

.Read from STDIN and write to STDOUT.
[source]
----
vulnlog suppress --reporter trivy - -o - < full-example.vl.yaml > .myTrivy
----

NOTE: Writing to stdout with `-o -` requires `--reporter` to select a single reporter.
Multiple suppression files cannot be written to stdout simultaneously.
