// Copyright the Vulnlog contributors
// SPDX-License-Identifier: Apache-2.0

package dev.vulnlog.lib.codec.suppression

import dev.vulnlog.lib.model.ReporterType
import dev.vulnlog.lib.model.VulnId
import dev.vulnlog.lib.model.suppression.SuppressionEntry
import dev.vulnlog.lib.model.suppression.SuppressionFormat
import dev.vulnlog.lib.model.suppression.SuppressionList
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldStartWith
import java.time.LocalDate

class SuppressionEncoderTest :
    FunSpec({

        test("the generic format is JSON with expires_at and statement, without a header") {
            val entry = SuppressionEntry(VulnId.Cve("CVE-2026-1111"), LocalDate.of(2026, 8, 1), "not reachable")
            val list = SuppressionList(SuppressionFormat.Generic(ReporterType.GRYPE), setOf(entry))

            val content = SuppressionEncoder.encode(list)

            content shouldBe
                """
                {
                  "vulnerabilities" : [ {
                    "id" : "CVE-2026-1111",
                    "expires_at" : "2026-08-01",
                    "statement" : "not reachable"
                  } ]
                }
                """.trimIndent()
        }

        test("the YAML and TOML formats start with the generated-by header") {
            val formats = listOf(SuppressionFormat.Trivy, SuppressionFormat.Snyk, SuppressionFormat.CargoAudit)

            val contents = formats.map { format -> SuppressionEncoder.encode(SuppressionList(format, emptySet())) }

            contents.forEach { it shouldStartWith "# Generated by Vulnlog (https://vulnlog.dev). DO NOT EDIT.\n" }
        }
    })
