name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  discussions: write

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_notes_body: ${{ steps.release-notes.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/changelog.toml
          args: --tag ${{ github.ref }} --github-repo ${{ github.repository }}
        env:
          OUTPUT: CHANGELOG.md
      - name: Commit CHANGELOG.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs(changelog): update for ${{ github.ref }}" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main
      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        id: release-notes
        with:
          config: .github/release-notes.toml
          args: --latest --github-repo ${{ github.repository }}

  publish-dsl:
    name: Publish DSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish DSL to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          ./gradlew clean publishAndReleaseToMavenCentral --no-configuration-cache -PappVersion="$VERSION"

  publish-gradle-plugin:
    name: Publish Gradle plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish Gradle plugin
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          ./gradlew :gradle-plugin:publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PLUGIN_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PLUGIN_SECRET }} -PappVersion="$VERSION"

  publish-release:
    name: Publish release
    needs: [ generate-changelog, publish-dsl, publish-gradle-plugin ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Create project ZIP
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          ./gradlew clean :cli:distZip -PappVersion="$VERSION"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Vulnlog ${{ github.ref_name }}"
          prerelease: true
          body: |
            ${{needs.generate-changelog.outputs.release_notes_body}}

            👉 Full Changelog: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
          files: cli-app/cli/build/distributions/*.zip
      - name: Create a new GitHub discussion
        id: create-discussion
        uses: abirismyname/create-discussion@main
        with:
          title: Vulnlog ${{ github.ref_name }} is released
          body: |
            Vulnlog ${{ github.ref_name }} is released!
            
            For a full description of changes, take a look at our [release notes](https://github.com/vulnlog/vulnlog/releases/tag/${{ github.ref_name }}).
          category-name: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}
