name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      changelog_body: ${{ steps.changelog.outputs.content }}
      release_notes_body: ${{ steps.release-notes.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: changelog
        with:
          config: .github/changelog.toml
          args: --tag ${{ github.ref }} --github-repo ${{ github.repository }}
      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        id: release-notes
        with:
          config: .github/release-notes.toml
          args: --latest --github-repo ${{ github.repository }}

  publish-dsl:
    name: Publish DSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish DSL to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew clean publishAndReleaseToMavenCentral --no-configuration-cache

  publish-gradle-plugin:
    name: Publish Gradle plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish Gradle plugin
        run: ./gradlew :gradle-plugin:publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PLUGIN_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PLUGIN_SECRET }}

  test-changelog:
    name: Test changelog output
    needs: generate-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Print changelog
        run: echo "${{needs.generate-changelog.outputs.changelog_body}}"
      - name: Print release notes
        run: echo "${{needs.generate-changelog.outputs.release_notes_body}}"
