# On every pull request to main
name: Build and test project

on:
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  assembleCheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run all tests
        run: ./gradlew check
