name: Release CLI app

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 1.0.0)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so git-cliff can see all commits

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          architecture: x64

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check the project
        run: ./gradlew check

      - name: Set version
        run: echo "${{ github.event.inputs.version }}" > version.txt

      - name: Create project ZIP
        run: ./gradlew clean :cli:distZip -PappVersion=$(cat version.txt)

      - name: Generate Release Notes
        id: notes
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/release-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CHANGELOG.md
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff.toml
          args: --tag v${{ github.event.inputs.version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit CHANGELOG.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md version.txt
          git commit -m "docs(changelog): update for v${{ github.event.inputs.version }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: "Vulnlog v${{ github.event.inputs.version }}"
          body: |
            ${{ steps.notes.outputs.changelog }}

            👉 Full Changelog: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
          files: cli-app/cli/build/distributions/*.zip
